# Generated by Django 3.2 on 2021-04-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('musicapp', '0002_alter_artist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
