# Generated by Django 3.2 on 2021-04-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_artist_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='copyrighted',
        ),
    ]
