# Generated by Django 3.2 on 2021-04-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('musicapp', '0003_artist_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_name',
        ),
    ]
