# Generated by Django 3.2 on 2021-04-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20210426_2030'),
        ('musicapp', '0004_remove_detail_copyrighted'),
    ]

    operations = [
    ]
